# BASIC AUTH
proxy:
  ### PERSONALIZATION ###
  title: "ShinyStudio: ${SITEPORT}"
  hide-navbar: false
  ### AUTHENTICATION ###
  admin-groups: ['admins', 'superadmins']
  authentication: simple
  users:
  - name: superadmin
    password: superadmin
    groups: superadmins
  - name: admin
    password: admin
    groups: admins
  - name: user
    password: user
    groups: readers
  ### DANGER ZONE ###
  port: 8080 # LEAVE ME ALONE
  landing-page: /
  logo-url: file:///opt/shinyproxy/templates/grid-layout/assets/img/logo.png
  favicon-path: /opt/shinyproxy/templates/grid-layout/assets/img/logo.png
  template-path: ./templates/grid-layout
  container-wait-time: 30000
  heartbeat-rate: 15000
  heartbeat-timeout: 120000
  usage-stats-url: http://influxdb:8086/write?db=shinyproxy_usagestats
  docker:
    internal-networking: true
  specs:
    - id: reports
      display-name: Apps & Reports
      logo-url: 'fas fa-chart-line'
      container-image: "shinystudio_${SITEPORT}_shinystudio"
      container-cmd: ["/start.sh", "shiny-server"]
      container-network: "shinystudio_${SITEPORT}_default"
      container-volumes:
        - "${CONTENTPATH}/sites/${SITEPORT}/_apps:/srv/shiny-server:z"
        - "shinystudio_${SITEPORT}_r_libraries:/r-libs"
        - "shinystudio_${SITEPORT}_py_environment:/pyenv"
        - 'shinystudio_${SITEPORT}_pwsh_modules:/home/#{proxy.userId}/.local/share/powershell/Modules'
      access-groups: [ 'superadmins', 'admins', 'readers' ]
      container-env:
        USER: "#{proxy.userId}"
        USERID: ${USERID}
    - id: documents
      display-name: Documents
      logo-url: 'fas fa-file-alt'
      container-image: "shinystudio_${SITEPORT}_shinystudio"
      container-cmd: ["/start.sh", "shiny-server"]
      container-network: "shinystudio_${SITEPORT}_default"
      container-volumes:
        - "${CONTENTPATH}/sites/${SITEPORT}/_docs:/srv/shiny-server:z"
        - "shinystudio_${SITEPORT}_r_libraries:/r-libs"
        - "shinystudio_${SITEPORT}_py_environment:/pyenv"
        - 'shinystudio_${SITEPORT}_pwsh_modules:/home/#{proxy.userId}/.local/share/powershell/Modules'
      access-groups: [ 'superadmins', 'admins', 'readers' ]
      container-env:
        USER: "#{proxy.userId}"
        USERID: ${USERID}
    - id: personal
      display-name: Personal
      logo-url: 'far fa-folder-open'
      container-image: "shinystudio_${SITEPORT}_shinystudio"
      container-cmd: ["/start.sh", "shiny-server"]
      container-network: "shinystudio_${SITEPORT}_default"
      container-volumes:
        - "${CONTENTPATH}/users/#{proxy.userId}:/srv/shiny-server:z"
        - "shinystudio_${SITEPORT}_r_libraries:/r-libs"
        - "shinystudio_${SITEPORT}_py_environment:/pyenv"
        - 'shinystudio_${SITEPORT}_pwsh_modules:/home/#{proxy.userId}/.local/share/powershell/Modules'
      access-groups: [ 'superadmins', 'admins', 'readers' ]
      container-env:
        USER: "#{proxy.userId}"
        USERID: ${USERID}
    - id: rstudio
      display-name: RStudio
      logo-url: 'fab fa-r-project'
      container-image: "shinystudio_${SITEPORT}_shinystudio"
      container-cmd: ["/start.sh", "rstudio"]
      container-network: "shinystudio_${SITEPORT}_default"
      container-volumes:
        - "${CONTENTPATH}/sites/${SITEPORT}:/home/#{proxy.userId}/__ShinyStudio__:z"
        - "${CONTENTPATH}/users/#{proxy.userId}:/home/#{proxy.userId}/__Personal__:z"
        - "${CONTENTPATH}/users/#{proxy.userId}/.rstudio:/home/#{proxy.userId}/.rstudio/monitored/user-settings:z"
        - "shinystudio_${SITEPORT}_r_libraries:/r-libs"
        - "shinystudio_${SITEPORT}_py_environment:/pyenv"
        - 'shinystudio_${SITEPORT}_pwsh_modules:/home/#{proxy.userId}/.local/share/powershell/Modules'
      container-env:
        USER: "#{proxy.userId}"
        USERID: ${USERID}
      description: Full Screen
      port: 8787
      access-groups: [ 'admins' ]
    - id: superrstudio
      display-name: RStudio
      logo-url: 'fab fa-r-project'
      container-image: "shinystudio_${SITEPORT}_shinystudio"
      container-cmd: ["/start.sh", "rstudio"]
      container-network: "shinystudio_${SITEPORT}_default"
      container-volumes:
        - "${CONTENTPATH}:/home/#{proxy.userId}/__ShinyStudio__:z"
        - "${CONTENTPATH}/users/#{proxy.userId}:/home/#{proxy.userId}/__Personal__:z"
        - "${CONTENTPATH}/users/#{proxy.userId}/.rstudio:/home/#{proxy.userId}/.rstudio/monitored/user-settings:z"
        - "shinystudio_${SITEPORT}_r_libraries:/r-libs"
        - "shinystudio_${SITEPORT}_py_environment:/pyenv"
        - 'shinystudio_${SITEPORT}_pwsh_modules:/home/#{proxy.userId}/.local/share/powershell/Modules'
      container-env:
        USER: "#{proxy.userId}"
        USERID: ${USERID}
        SITEPORT: ${SITEPORT}
      description: Full Screen
      port: 8787
      access-groups: [ 'superadmins' ]
    - id: vscode
      display-name: Visual Studio Code
      logo-url: 'fas fa-terminal'
      container-image: "shinystudio_${SITEPORT}_shinystudio"
      container-cmd: ["/start.sh", "vscode"]
      container-network: "shinystudio_${SITEPORT}_default"
      container-volumes:
        - "${CONTENTPATH}/sites/${SITEPORT}:/home/#{proxy.userId}/__ShinyStudio__:z"
        - "${CONTENTPATH}/users/#{proxy.userId}:/home/#{proxy.userId}/__Personal__:z"
        - "${CONTENTPATH}/users/#{proxy.userId}/.vscode:/home/#{proxy.userId}/.local/share/code-server:z"
        - "shinystudio_${SITEPORT}_r_libraries:/r-libs"
        - "shinystudio_${SITEPORT}_py_environment:/pyenv"
        - 'shinystudio_${SITEPORT}_pwsh_modules:/home/#{proxy.userId}/.local/share/powershell/Modules'
      container-env:
        USER: "#{proxy.userId}"
        USERID: ${USERID}
      description: Full Screen
      port: 8443
      access-groups: [ 'admins' ]
    - id: supervscode
      display-name: Visual Studio Code
      logo-url: 'fas fa-terminal'
      container-image: "shinystudio_${SITEPORT}_shinystudio"
      container-cmd: ["/start.sh", "vscode"]
      container-network: "shinystudio_${SITEPORT}_default"
      container-volumes:
        - "${CONTENTPATH}:/home/#{proxy.userId}/__ShinyStudio__:z"
        - "${CONTENTPATH}/users/#{proxy.userId}:/home/#{proxy.userId}/__Personal__:z"
        - "${CONTENTPATH}/users/#{proxy.userId}/.vscode:/home/#{proxy.userId}/.local/share/code-server:z"
        - "shinystudio_${SITEPORT}_r_libraries:/r-libs"
        - "shinystudio_${SITEPORT}_py_environment:/pyenv"
        - 'shinystudio_${SITEPORT}_pwsh_modules:/home/#{proxy.userId}/.local/share/powershell/Modules'
      container-env:
        USER: "#{proxy.userId}"
        USERID: ${USERID}
        SITEPORT: ${SITEPORT}
      description: Full Screen
      port: 8443
      access-groups: [ 'superadmins' ]
